package ru.yandex.javacourse.schedule.manager;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.List;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import ru.yandex.javacourse.schedule.tasks.Epic;
import ru.yandex.javacourse.schedule.tasks.Subtask;
import ru.yandex.javacourse.schedule.tasks.Task;
import ru.yandex.javacourse.schedule.tasks.TaskStatus;

public class InMemoryTaskManagerTest {

    TaskManager manager;

    @BeforeEach
    public void initManager(){
        manager = Managers.getDefault();
    }

    @Test
    public void testAddTask() {
        Task task = new Task("Task1", "Task1 description", TaskStatus.NEW);
        manager.addNewTask(task);
        assertEquals(1, manager.getTasks().size(), "task should be added");
        Task addedTask = manager.getTasks().get(0);
        assertEquals(task, addedTask, "added task id should be set");
        Task byIdTask = manager.getTask(task.getId());
        assertEquals(task, byIdTask, "added task id should be found");
    }

    @Test
    public void testAddTaskWithId(){
        Task task = new Task(42, "Task1", "Task1 description", TaskStatus.NEW);
        manager.addNewTask(task);
        assertEquals(1, manager.getTasks().size(), "task should be added");
        Task addedTask = manager.getTasks().get(0);
        assertEquals(task, addedTask, "predefined task id should be set");
    }

    @Test
    public void testAddTaskWithAndWithoutId(){
        Task task1 = new Task("Task1", "Task1 description", TaskStatus.NEW);
        Task task2 = new Task(3, "Task2", "Task2 description", TaskStatus.NEW);
        manager.addNewTask(task1);
        manager.addNewTask(task2);
        assertEquals(2, manager.getTasks().size(), "lost a task with predefined id");
        assertEquals(1, task1.getId(), "autogenerated id should be 1");
        assertEquals(3, task2.getId(), "task predefined id should not change");
    }

    @Test
    public void testAddTaskWithExistingId(){
        Task task1 = new Task(1, "Task1", "Task1 description", TaskStatus.NEW);
        Task task2 = new Task(1, "Task2", "Task2 description", TaskStatus.NEW);
        manager.addNewTask(task1);
        assertThrows(IllegalArgumentException.class, () -> manager.addNewTask(task2));
    }

    @Test
    public void testCheckTaskNotChangedAfterAddTask() {
        int id = 1;
        String name = "Task1";
        String description = "Task1 description";
        TaskStatus status = TaskStatus.NEW;
        Task task1before = new Task(id, name, description, status);
        manager.addNewTask(task1before);
        Task task1after = manager.getTask(task1before.getId());
        assertEquals(id, task1after.getId());
        assertEquals(description, task1after.getDescription());
        assertEquals(status, task1after.getStatus());
        assertEquals(name, task1after.getName());
    }

    @Test
    void testAddEpicAndSubtasksAndUpdateEpicStatus() {
        Epic epic = new Epic("Epic1", "Epic1 description");
        int epicId = manager.addNewEpic(epic);
        Subtask subtask1 = new Subtask("Subtask1", "Subtask1 description", TaskStatus.NEW, epicId);
        Subtask subtask2 = new Subtask("Subtask2", "Subtask2 description", TaskStatus.NEW, epicId);
        manager.addNewSubtask(subtask1);
        manager.addNewSubtask(subtask2);
        Epic updated = manager.getEpic(epicId);
        assertEquals(TaskStatus.NEW, updated.getStatus());
        subtask1.setStatus(TaskStatus.DONE);
        manager.updateSubtask(subtask1);
        updated = manager.getEpic(epicId);
        assertEquals(TaskStatus.IN_PROGRESS, updated.getStatus());
        subtask2.setStatus(TaskStatus.DONE);
        manager.updateSubtask(subtask2);
        updated = manager.getEpic(epicId);
        assertEquals(TaskStatus.DONE, updated.getStatus());
    }

    @Test
    void testDeleteSubtaskAndUpdateEpicStatus() {
        Epic epic = new Epic("Epic1", "Epic1 description");
        int epicId = manager.addNewEpic(epic);
        Subtask subtask1 = new Subtask("Subtask1", "Subtask1 description", TaskStatus.DONE, epicId);
        int subtask1Id = manager.addNewSubtask(subtask1);
        assertEquals(TaskStatus.DONE, manager.getEpic(epicId).getStatus());
        manager.deleteSubtask(subtask1Id);
        assertEquals(TaskStatus.NEW, manager.getEpic(epicId).getStatus());
    }

    @Test
    void testCleanEpicIdsAfterSubtaskDeletion() {
        Epic epic = new Epic("Epic1", "Epic1 description");
        int epicId = manager.addNewEpic(epic);
        Subtask subtask = new Subtask("Subtask1", "Subtask1 description", TaskStatus.NEW, epicId);
        int subtaskId = manager.addNewSubtask(subtask);
        manager.deleteSubtask(subtaskId);
        Epic updated = manager.getEpic(epicId);
        assertTrue(updated.getSubtaskIds().isEmpty());
    }

    @Test
    void testStoreHistoryOfViewedTasks() {
        Task task1 = new Task("Task1", "Task1 description", TaskStatus.NEW);
        Task task2 = new Task("Task2", "Task2 description", TaskStatus.NEW);
        manager.addNewTask(task1);
        manager.addNewTask(task2);
        manager.getTask(task1.getId());
        manager.getTask(task2.getId());
        List<Task> history = manager.getHistory();
        assertEquals(2, history.size());
    }

    @Test
    void testRemoveEpicWithAllSubtasks() {
        Epic epic = new Epic("Epic1", "Epic1 description");
        int epicId = manager.addNewEpic(epic);
        Subtask subtask1 = new Subtask("Subtask1", "Subtask1 description", TaskStatus.NEW, epicId);
        manager.addNewSubtask(subtask1);
        manager.deleteEpic(epicId);
        assertTrue(manager.getSubtasks().isEmpty());
        assertNull(manager.getEpic(epicId));
    }

    @Test
    void testNotAddSubtaskIfEpicDoesNotExist() {
        Subtask subtask = new Subtask("Subtask1", "Subtask1 description", TaskStatus.NEW, 999);
        assertNull(manager.addNewSubtask(subtask));
    }

    @Test
    void testDeleteAllTasksAndSubtasks() {
        manager.addNewTask(new Task("Task1", "Task1 description", TaskStatus.NEW));
        manager.addNewTask(new Task("Task2", "Task2 description", TaskStatus.NEW));
        Epic epic = new Epic("Epic1", "Epic1 description");
        int epicId = manager.addNewEpic(epic);
        manager.addNewSubtask(new Subtask("Subtask1", "Subtask1 description", TaskStatus.NEW, epicId));
        manager.deleteTasks();
        manager.deleteSubtasks();
        manager.deleteEpics();
        assertTrue(manager.getTasks().isEmpty());
        assertTrue(manager.getSubtasks().isEmpty());
        assertTrue(manager.getEpics().isEmpty());
    }

    @Test
    void testUpdateExistingTask() {
        Task task = new Task("Task1", "Task1 description", TaskStatus.NEW);
        int id = manager.addNewTask(task);
        task.setStatus(TaskStatus.DONE);
        manager.updateTask(task);
        assertEquals(TaskStatus.DONE, manager.getTask(id).getStatus());
        assertEquals(1, manager.getTasks().size());
    }
}
