package ru.yandex.javacourse.schedule.manager;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.time.Duration;
import java.time.LocalDateTime;
import java.util.List;
import org.junit.jupiter.api.Test;
import ru.yandex.javacourse.schedule.exceptions.IntersectionException;
import ru.yandex.javacourse.schedule.exceptions.NotFoundException;
import ru.yandex.javacourse.schedule.tasks.Epic;
import ru.yandex.javacourse.schedule.tasks.Subtask;
import ru.yandex.javacourse.schedule.tasks.Task;
import ru.yandex.javacourse.schedule.tasks.TaskStatus;

abstract class TaskManagerTest<T extends TaskManager> {
    T taskManager;

    @Test
    void testAddAndGetTask() {
        Task task = new Task("Task1", "Task1 description", TaskStatus.NEW);
        taskManager.addNewTask(task);
        assertEquals(1, taskManager.getTasks().size(), "task should be added");
        Task addedTask = taskManager.getTasks().get(0);
        assertEquals(task, addedTask, "added task id should be set");
        Task byIdTask = taskManager.getTask(task.getId());
        assertEquals(task, byIdTask, "added task id should be found");
    }

    @Test
    public void testAddTaskWithId(){
        Task task = new Task(42, "Task1", "Task1 description", TaskStatus.NEW);
        taskManager.addNewTask(task);
        assertEquals(1, taskManager.getTasks().size(), "task should be added");
        Task addedTask = taskManager.getTasks().get(0);
        assertEquals(task, addedTask, "predefined task id should be set");
    }

    @Test
    public void testAddTaskWithAndWithoutId(){
        Task task1 = new Task("Task1", "Task1 description", TaskStatus.NEW);
        Task task2 = new Task(3, "Task2", "Task2 description", TaskStatus.NEW);
        taskManager.addNewTask(task1);
        taskManager.addNewTask(task2);
        assertEquals(2, taskManager.getTasks().size(), "lost a task with predefined id");
        assertEquals(1, task1.getId(), "autogenerated id should be 1");
        assertEquals(3, task2.getId(), "task predefined id should not change");
    }

    @Test
    public void testAddTaskWithExistingId(){
        Task task1 = new Task(1, "Task1", "Task1 description", TaskStatus.NEW);
        Task task2 = new Task(1, "Task2", "Task2 description", TaskStatus.NEW);
        taskManager.addNewTask(task1);
        assertThrows(IllegalArgumentException.class, () -> taskManager.addNewTask(task2));
    }

    @Test
    public void testCheckTaskNotChangedAfterAddTask() {
        int id = 1;
        String name = "Task1";
        String description = "Task1 description";
        TaskStatus status = TaskStatus.NEW;
        Task task1before = new Task(id, name, description, status);
        taskManager.addNewTask(task1before);
        Task task1after = taskManager.getTask(task1before.getId());
        assertEquals(id, task1after.getId());
        assertEquals(description, task1after.getDescription());
        assertEquals(status, task1after.getStatus());
        assertEquals(name, task1after.getName());
    }

    @Test
    void testAddEpicAndSubtasksAndUpdateEpicStatus() {
        Epic epic = new Epic("Epic1", "Epic1 description");
        int epicId = taskManager.addNewEpic(epic);
        Subtask subtask1 = new Subtask("Subtask1", "Subtask1 description", TaskStatus.NEW, epicId);
        Subtask subtask2 = new Subtask("Subtask2", "Subtask2 description", TaskStatus.NEW, epicId);
        taskManager.addNewSubtask(subtask1);
        taskManager.addNewSubtask(subtask2);
        Epic updated = taskManager.getEpic(epicId);
        assertEquals(TaskStatus.NEW, updated.getStatus());
        subtask1.setStatus(TaskStatus.DONE);
        taskManager.updateSubtask(subtask1);
        updated = taskManager.getEpic(epicId);
        assertEquals(TaskStatus.IN_PROGRESS, updated.getStatus());
        subtask2.setStatus(TaskStatus.DONE);
        taskManager.updateSubtask(subtask2);
        updated = taskManager.getEpic(epicId);
        assertEquals(TaskStatus.DONE, updated.getStatus());
    }

    @Test
    void testDeleteSubtaskAndUpdateEpicStatus() {
        Epic epic = new Epic("Epic1", "Epic1 description");
        int epicId = taskManager.addNewEpic(epic);
        Subtask subtask1 = new Subtask("Subtask1", "Subtask1 description", TaskStatus.DONE, epicId);
        int subtask1Id = taskManager.addNewSubtask(subtask1);
        assertEquals(TaskStatus.DONE, taskManager.getEpic(epicId).getStatus());
        taskManager.deleteSubtask(subtask1Id);
        assertEquals(TaskStatus.NEW, taskManager.getEpic(epicId).getStatus());
    }

    @Test
    void testCleanEpicIdsAfterSubtaskDeletion() {
        Epic epic = new Epic("Epic1", "Epic1 description");
        int epicId = taskManager.addNewEpic(epic);
        Subtask subtask = new Subtask("Subtask1", "Subtask1 description", TaskStatus.NEW, epicId);
        int subtaskId = taskManager.addNewSubtask(subtask);
        taskManager.deleteSubtask(subtaskId);
        Epic updated = taskManager.getEpic(epicId);
        assertTrue(updated.getSubtaskIds().isEmpty());
    }

    @Test
    void testStoreHistoryOfViewedTasks() {
        Task task1 = new Task("Task1", "Task1 description", TaskStatus.NEW);
        Task task2 = new Task("Task2", "Task2 description", TaskStatus.NEW);
        taskManager.addNewTask(task1);
        taskManager.addNewTask(task2);
        taskManager.getTask(task1.getId());
        taskManager.getTask(task2.getId());
        List<Task> history = taskManager.getHistory();
        assertEquals(2, history.size());
    }

    @Test
    void testRemoveEpicWithAllSubtasks() {
        Epic epic = new Epic("Epic1", "Epic1 description");
        int epicId = taskManager.addNewEpic(epic);
        Subtask subtask1 = new Subtask("Subtask1", "Subtask1 description", TaskStatus.NEW, epicId);
        taskManager.addNewSubtask(subtask1);
        taskManager.deleteEpic(epicId);
        assertTrue(taskManager.getSubtasks().isEmpty());
        assertThrows(NotFoundException.class, () -> taskManager.getEpic(epicId));
    }

    @Test
    void testNotAddSubtaskIfEpicDoesNotExist() {
        Subtask subtask = new Subtask("Subtask1", "Subtask1 description", TaskStatus.NEW, 999);
        assertNull(taskManager.addNewSubtask(subtask));
    }

    @Test
    void testDeleteAllTasksAndSubtasks() {
        taskManager.addNewTask(new Task("Task1", "Task1 description", TaskStatus.NEW));
        taskManager.addNewTask(new Task("Task2", "Task2 description", TaskStatus.NEW));
        Epic epic = new Epic("Epic1", "Epic1 description");
        int epicId = taskManager.addNewEpic(epic);
        taskManager.addNewSubtask(new Subtask("Subtask1", "Subtask1 description", TaskStatus.NEW, epicId));
        taskManager.deleteTasks();
        taskManager.deleteSubtasks();
        taskManager.deleteEpics();
        assertTrue(taskManager.getTasks().isEmpty());
        assertTrue(taskManager.getSubtasks().isEmpty());
        assertTrue(taskManager.getEpics().isEmpty());
    }

    @Test
    void testUpdateExistingTask() {
        Task task = new Task("Task1", "Task1 description", TaskStatus.NEW);
        int id = taskManager.addNewTask(task);
        task.setStatus(TaskStatus.DONE);
        taskManager.updateTask(task);
        assertEquals(TaskStatus.DONE, taskManager.getTask(id).getStatus());
        assertEquals(1, taskManager.getTasks().size());
    }

    @Test
    void testEpicDurationAndTimes() {
        Epic epic = new Epic("Epic1", "Epic1 description");
        int epicId = taskManager.addNewEpic(epic);
        Subtask s1 = new Subtask("Subtask1", "Subtask1 description", TaskStatus.NEW, epicId,
            Duration.ofMinutes(30),
            LocalDateTime.of(2025,1,1,10,0));
        Subtask s2 = new Subtask("Subtask2", "Subtask2 description", TaskStatus.NEW, epicId,
            Duration.ofMinutes(50),
            LocalDateTime.of(2025,1,1,9,0));
        taskManager.addNewSubtask(s1);
        taskManager.addNewSubtask(s2);
        Epic loaded = taskManager.getEpic(epicId);
        assertEquals(Duration.ofMinutes(80), loaded.getDuration());
        assertEquals(LocalDateTime.of(2025,1,1,9,0), loaded.getStartTime());
        assertEquals(LocalDateTime.of(2025,1,1,10,30), loaded.getEndTime());
    }

    @Test
    void testPrioritizedTasksOrder() {
        Task t1 = new Task("Task1", "Task1 description", TaskStatus.NEW,
            Duration.ofMinutes(10),
            LocalDateTime.of(2025,1,1,11,0));
        Task t2 = new Task("Task2", "Task2 description", TaskStatus.NEW,
            Duration.ofMinutes(10),
            LocalDateTime.of(2025,1,1,9,0));
        Task t3 = new Task("Task3", "Task3 description", TaskStatus.NEW,
            Duration.ofMinutes(10),
            LocalDateTime.of(2025,1,1,15,0));
        taskManager.addNewTask(t1);
        taskManager.addNewTask(t2);
        taskManager.addNewTask(t3);
        List<Task> sorted = taskManager.getPrioritizedTasks();
        assertEquals("Task2", sorted.get(0).getName());
        assertEquals("Task1", sorted.get(1).getName());
        assertEquals("Task3", sorted.get(2).getName());
    }

    @Test
    void testTaskWithoutStartTimeIsNotPrioritized() {
        Task t = new Task("Task1", "Task1 description", TaskStatus.NEW);
        taskManager.addNewTask(t);
        assertTrue(taskManager.getPrioritizedTasks().isEmpty());
    }

    @Test
    void testAddTasksWhenNoIntersection() {
        Task t1 = new Task("Task1", "Task1 description", TaskStatus.NEW,
            Duration.ofMinutes(30),
            LocalDateTime.of(2025,1,1,10,0));
        Task t2 = new Task("Task2", "Task2 description", TaskStatus.NEW,
            Duration.ofMinutes(30),
            LocalDateTime.of(2025,1,1,11,0));
        taskManager.addNewTask(t1);
        taskManager.addNewTask(t2);
        assertEquals(2, taskManager.getTasks().size());
        assertEquals(2, taskManager.getPrioritizedTasks().size());
    }

    @Test
    void testThrowForOverlapStartInside() {
        Task t1 = new Task("Task1", "Task1 description", TaskStatus.NEW,
            Duration.ofMinutes(60),
            LocalDateTime.of(2025,1,1,10,0));
        Task t2 = new Task("Task2", "Task2 description", TaskStatus.NEW,
            Duration.ofMinutes(30),
            LocalDateTime.of(2025,1,1,10,30));
        taskManager.addNewTask(t1);
        assertThrows(
            IntersectionException.class,
            () -> taskManager.addNewTask(t2)
        );
    }

    @Test
    void testThrowForOverlapEndInside() {
        Task t1 = new Task("Task1", "Task1 description", TaskStatus.NEW,
            Duration.ofMinutes(60),
            LocalDateTime.of(2025,1,1,10,0));
        Task t2 = new Task("Task2", "Task2 description", TaskStatus.NEW,
            Duration.ofMinutes(60),
            LocalDateTime.of(2025,1,1,9,30));
        taskManager.addNewTask(t1);
        assertThrows(
            IntersectionException.class,
            () -> taskManager.addNewTask(t2)
        );
    }

    @Test
    void testThrowForTaskInsideOtherTask() {
        Task t1 = new Task("Task1", "Task1 description", TaskStatus.NEW,
            Duration.ofMinutes(60),
            LocalDateTime.of(2025,1,1,10,0));
        Task t2 = new Task("Task2", "Task2 description", TaskStatus.NEW,
            Duration.ofMinutes(15),
            LocalDateTime.of(2025,1,1,10,30));
        taskManager.addNewTask(t1);
        assertThrows(
            IntersectionException.class,
            () -> taskManager.addNewTask(t2)
        );
    }
}
